### ISSUE TITLE
Riesling should have Floral (Blossom) in Flavour

### ISSUE THREAD

**Issue by dereklei** [luksow/wset#2]
In the book it says Riesling has "floral (blossom)" when Riesling grapes are just-ripe.

**Comment by luksow** [comment]
Hi! Thanks for the issue. I've just looked up Riesling (chapter 8, p. 31) in the book and it says in the 2nd paragraph:

> The specific fruit flavours in the wine vary according to the level of ripeness in the grapes at the time of harvest. Grapes that are just-ripe produce wines with flavours of green fruit (apple, pear) and citrus (lemon, lime). Extra-ripe grapes give flavours of stone fruit (peach, apricot) tropical fruit (mango, pineapple) and sometimes even dried fruit (dried apricots, raisins).

So if you could please clarify where is the piece of information that you mentioned?

**Comment by dschaub** [comment]
Hi! This is an awesome resource, thanks! Just wandering through here and double checked, my book does have "floral (blossom)" in the list of flavors for just-ripe Riesling. I'm assuming this is an edition difference - my book says "Issue 2" on the back and has a copyright of 2023.

**Comment by dschaub** [comment]
It's nearly identical, just that difference and no raisin taste on extra-ripe:

> The specific fruit flavours in the wine vary according to the level of ripeness in the grapes at the time of harvest. Grapes that are just-ripe produce wines with green fruit (apple, pear), citrus (lemon, lime) and floral (blossom) characteristics. Extra-ripe grapes give flavours of stone fruit (peach, apricot), tropical fruit (mango, pineapple) and sometimes even dried fruit (dried apricots).

I assume these little differences are all over the book, so a "based on Issue 1 (2019)" near the bottom would be way easier 😂  I can't imagine the changes are enough to make much of a difference on the exam (which I'm taking in a month).

**Comment by luksow** [comment]
@dschaub thanks! Updated in https://github.com/luksow/wset/commit/3a3a27877248063081e46395f12f77df13de72ff

I guess I should get a new copy for myself :thinking: 

Good luck with your exam and have fun exploring fascinating wine world!

By the way, I plan to create more resources especially since I'm planning WSET 3 next year, so make sure to keep a bookmark handy :wink:

**Comment by luksow** [comment]
@dschaub: cool! I'll definitely have a look. Thanks!
